# Generated by Django 4.0.2 on 2023-03-31 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_addresses', '0002_alter_shippingaddress_line2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='country',
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(choices=[('Armenia', 'Armenia'), ('Barrancabermeja', 'Barrancabermeja'), ('Barranquilla', 'Barranquilla'), ('Bogotá', 'Bogotá'), ('Bucaramanga', 'Bucaramanga'), ('Buga', 'Buga'), ('Cali', 'Cali'), ('Chía', 'Chía'), ('Cúcuta', 'Cúcuta'), ('Duitama', 'Duitama'), ('Girardot', 'Girardot'), ('Honda', 'Honda'), ('Ibagué', 'Ibagué'), ('Ipiales', 'Ipiales'), ('Jamundí', 'Jamundí'), ('Leticia', 'Leticia'), ('Manizales', 'Manizales'), ('Mariquita', 'Mariquita'), ('Medellín', 'Medellín'), ('Mompox', 'Mompox'), ('Montería', 'Montería'), ('Murillo', 'Murillo'), ('Neiva', 'Neiva'), ('Pasto', 'Pasto'), ('Pereira', 'Pereira'), ('San Andrés', 'San Andrés'), ('Santa Marta', 'Santa Marta'), ('Valledupar', 'Valledupar'), ('Barranquila', 'Barranquila'), ('Villavicencio', 'Villavicencio'), ('Zipaquirá', 'Zipaquirá')], max_length=50),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='postal_code',
            field=models.IntegerField(max_length=6),
        ),
    ]
