# Generated by Django 4.1.7 on 2023-03-30 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_alter_cart_cart_id_alter_cart_products_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['id'], 'verbose_name': 'Carrito', 'verbose_name_plural': 'Carritos'},
        ),
    ]
