# Generated by Django 4.0.2 on 2023-03-24 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Nombre del cliente')),
                ('phone', models.IntegerField(max_length=10, verbose_name='Telefono del cliente')),
                ('address', models.CharField(max_length=24, verbose_name='Direcion del cliente ')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'PROVEEDOR',
                'ordering': ['id'],
            },
        ),
    ]
