# Generated by Django 4.0.2 on 2023-03-24 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(max_length=24, verbose_name='Direcion del cliente '),
        ),
    ]
