# Generated by Django 4.0.2 on 2023-03-24 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0002_alter_supplier_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(max_length=24, verbose_name='Direcion del proveedor '),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Nombre del proveedor'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.IntegerField(max_length=10, verbose_name='Telefono del proverdor'),
        ),
    ]
