# Generated by Django 4.0.2 on 2023-03-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo_codes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='discount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=8),
        ),
    ]
