# Generated by Django 4.0.2 on 2023-03-27 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compras',
            options={'ordering': ['producto'], 'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
    ]
