# Generated by Django 4.0.2 on 2023-03-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=20, verbose_name='Existencias'),
        ),
    ]
